// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvbT2cNz2W9kfo1CApGPM63HM87JMyBQ',
    appId: '1:82966115010:web:b5835e2dc07a0228b2015b',
    messagingSenderId: '82966115010',
    projectId: 'izahs-1ae32',
    authDomain: 'izahs-1ae32.firebaseapp.com',
    storageBucket: 'izahs-1ae32.firebasestorage.app',
    measurementId: 'G-RB3WFBMGJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19qltbuJWNrGRkDqGz7Zp0RCuz9HkTc8',
    appId: '1:82966115010:android:fd5b9bb0aa419adbb2015b',
    messagingSenderId: '82966115010',
    projectId: 'izahs-1ae32',
    storageBucket: 'izahs-1ae32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwL1POrBvXJC2s_jGFEsW88tLGtQb76Pk',
    appId: '1:82966115010:ios:438a8e00f34424a5b2015b',
    messagingSenderId: '82966115010',
    projectId: 'izahs-1ae32',
    storageBucket: 'izahs-1ae32.firebasestorage.app',
    iosClientId: '82966115010-nagg4ocdlhqbk44dr4l1ahoqm7p0ej39.apps.googleusercontent.com',
    iosBundleId: 'com.example.izahs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwL1POrBvXJC2s_jGFEsW88tLGtQb76Pk',
    appId: '1:82966115010:ios:438a8e00f34424a5b2015b',
    messagingSenderId: '82966115010',
    projectId: 'izahs-1ae32',
    storageBucket: 'izahs-1ae32.firebasestorage.app',
    iosClientId: '82966115010-nagg4ocdlhqbk44dr4l1ahoqm7p0ej39.apps.googleusercontent.com',
    iosBundleId: 'com.example.izahs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRvbT2cNz2W9kfo1CApGPM63HM87JMyBQ',
    appId: '1:82966115010:web:e9f3cd7484768ed9b2015b',
    messagingSenderId: '82966115010',
    projectId: 'izahs-1ae32',
    authDomain: 'izahs-1ae32.firebaseapp.com',
    storageBucket: 'izahs-1ae32.firebasestorage.app',
    measurementId: 'G-4G85XS5JSY',
  );

}